### ISSUE TITLE
TypeError: execv() arg 2 must contain only strings

### ISSUE THREAD

**Issue by Farhan-A** [fjruizruano/ngs-protocols#2]
Hi Francisco,

I was trying to use one of your scripts i.e count_reads_bam.py inorder to count the mapped reads for corresponding of 0B and 2B sorted bam files. I execute the script and give me some errors (please see the following), Could you please help me what is going on?

### farhan@charles:/storage/farhan/mexicanus-new-2018/alignments/ngs-protocols-master> ./count_reads_bam.py /storage/farhan/mexicanus-new-2018/alignments/0B_mex-bwa-transcriptome_local.sorted.bam.bam /storage/farhan/mexicanus-new-2018/alignments/2B_mex-bwa-transcriptome_local.sorted.bam.bam
Usage: count_reads_bam.py ListOfBamFiles
Traceback (most recent call last):
  File "./count_reads_bam.py", line 19, in <module>
    call("""samtools view -F 4 %s | awk {'print $3'} | uniq -c > %s""" % (name, name+".uniq"), shell=True)
  File "/usr/lib64/python2.6/subprocess.py", line 470, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.6/subprocess.py", line 623, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1141, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
farhan@charles:/storage/farhan/mexicanus-new-2018/alignments/ngs-protocols-master>

I am a beginner in bioinformatics, I will appreciate your help.

Thank you.
Farhan.

**Comment by fjruizruano** [comment]
Hi Farhan! Nice to (virtually) meet you.

First at all, you need to add the "join_multiple_lists.py" script in a binary folder.

The input for this script is a text list with the name of indexed BAM files. Easier way to get this file is having the BAM and BAI files in the same folder (if they are not, you can generate a symbolic link with "ln -s"). Then you can run a command like this:

ls *bam > bam_list.txt

And it generates a file named "bam_list.txt" with this content:

0B_mex-bwa-transcriptome_local.sorted.bam.bam
2B_mex-bwa-transcriptome_local.sorted.bam.bam

Then you would run the script like this:

count_reads_bam.py bam_list.txt

And it generates a "toico.txt" file with the read counts for each sequence and BAM file.

This would be all. If you need more help, do not hesitate to contact me.

Cheers,

**Comment by Farhan-A** [comment]
Hi Francisco,

Thanks alot.. The script working now. 

Farhan
