### ISSUE TITLE
NameError: name 'firstline' is not defined

### ISSUE THREAD

**Issue by ghost** [fjruizruano/ngs-protocols#4]
Trying execute fastq_edit_ids.py , but an error message appears:

Command line:
> python fastq_edit_ids.py reads_1.fastq reads_2.fastq

Error Message:
> Usage: fastq_edit_ids.py ListOfFastqFiles [GZ]
> 
> Format of the list: cosa_1.fastq(.gz) cosa_2.fastq.gz
> GZ: Optionally con write GZ if you prefer a .gz file as output instead of a .fastq file
> 
> @HISEQ:79:C6WYGACXX:3:2113:8652:85363 1:N:0:CAGATC
> Traceback (most recent call last):
>   File "fastq_edit_ids.py", line 44, in <module>
>     id = firstline[1]
> NameError: name 'firstline' is not defined

**Comment by fjruizruano** [comment]
Hi @Mol3cul4 !

You have to use as input a text file with the name of the FASTQ files, not the name of the FASTQ file themselves.

For example, you can create a file name "list.txt" with the following content:

reads_1.fastq
reads_2.fastq

And the command you have to type is:

$ python fastq_edit_ids.py list.txt

Please, let me know if it works.
Cheers!

**Comment by ghost** [comment]
Great! It works! 

Thank you so much.

Best regards sincerely.
