### ISSUE TITLE
Error during execution of fastq_edit_ids.py

### ISSUE THREAD

**Issue by pecosus** [fjruizruano/ngs-protocols#5]
Hi Francisco,

I was trying to use one of your scripts from satminer toolkit (fastq_edit_ids.py) but it returned the following error:

> genoma@bioinformatica:~/.emiliano$ fastq_edit_ids.py list GZ
> Usage: fastq_edit_ids.py ListOfFastqFiles
> Format of the files: cosa_1.fastq(.gz) cosa_2.fastq.gz
> 
> 5_1.fastq.gz
> 5_1.fastq.gz with uncorrect format, editing ids.
> /bin/sh: 1: fastool: not found
> 
> gzip: stdout: Broken pipe
> Traceback (most recent call last):
>   File "/usr/serverbin/satminer/fastq_edit_ids.py", line 52, in <module>
>     call("""sed -i 's/>%s/%s/g' %s > name.tmp""" % (identifier[1:],identifier,name,name), shell=True)
> TypeError: not all arguments converted during string formatting

"list" is a text file wich contains the names of fastq.gz files

I will appreciate your help or any suggestion.
Thank you!

**Comment by fjruizruano** [comment]
Hi @pecosus !

The fastq_edit_ids.py was updated two months ago and is not using fastool anymore. So, please, download again the script and try again. 

Let me know if it works.
Bests.

**Comment by pecosus** [comment]
Hi Francisco!

Thank you very much! It worked perfectly!

Bests.
